#!/bin/sh
# Auto-increment version.json on every commit
VERSION_FILE="version.json"
COMMIT_COUNT=$(git rev-list --count HEAD)
NEXT_VERSION=$((COMMIT_COUNT + 1))
echo "{\"version\":$NEXT_VERSION}" > "$VERSION_FILE"
git add "$VERSION_FILE"
